App\Entity\Location:
  properties:
    city:
      - NotBlank:
          groups: ['new', 'edit']
    country:
      - NotBlank:
          groups: ['new', 'edit']
    latitude:
      - NotBlank:
          groups: ['new', 'edit']
      - Range:
          min: -90
          max: 90
          groups: ['new', 'edit']
    longitude:
      - NotBlank:
          groups: ['new', 'edit']
      - Range:
          min: -180
          max: 180
          groups: ['new', 'edit']


App\Entity\MeteoData:
  properties:
    date:
      - NotBlank:
          groups: ['new', 'edit']
    highestTemperature:
      - NotBlank:
          groups: ['new', 'edit']
      - Range:
          min: -100
          max: 100
          groups: ['new', 'edit']
    lowestTemperature:
      - NotBlank:
          groups: ['new', 'edit']
      - Range:
          min: -100
          max: 100
          groups: ['new', 'edit']
    averageWindSpeed:
      - NotBlank:
          groups: ['new', 'edit']
      - Range:
          min: 0
          max: 400
          groups: ['new', 'edit']
    overcast:
      - NotBlank:
          groups: ['new', 'edit']
    precipitationKind:
      - NotBlank:
          groups: ['new', 'edit']
    precipitationIntensity:
      - NotBlank:
          groups: ['new', 'edit']
    humidity:
      - NotBlank:
          groups: ['new', 'edit']
      - Range:
          min: 0.00
          max: 1.00
          groups: ['new', 'edit']
    location:
      - NotBlank:
          groups: ['new', 'edit']